<?php

use App\Models\Tan90\MasterData\ApprovalWorkflow;
use App\Models\Tan90\MasterData\BusinessUnit;
use App\Models\Tan90\MasterData\ItemCategory;
use App\Models\Tan90\MasterData\LegalEntity;
use App\Models\Tan90\MasterData\Location;
use App\Models\Tan90\MasterData\Plant;
use App\Models\Tan90\MasterData\Rack;
use App\Models\Tan90\MasterData\Role;
use App\Models\Tan90\MasterData\Shelf;
use App\Models\Tan90\MasterData\Uom;
use App\Models\Tan90\MasterData\Vendor;
use App\Models\Tan90\MasterData\Warehouse;
use App\Models\Tan90\MasterData\WarehouseZone;

/**
 * Tan90 Master Data & Configuration — entity registry.
 *
 * This is the PHP-side equivalent of the demo's `registry` object in
 * assets/js/app.js: one declarative source of truth per master-data domain,
 * driving the generic list/detail/form controller and Blade views instead of
 * one controller + view set per entity. Adding a Phase 2 domain (e.g.
 * customers, machines) means adding a migration + model + one array entry
 * here — no new controller or view code.
 *
 * Field shape:
 *   'name'     => database column / request key
 *   'label'    => form field label
 *   'type'     => text|textarea|select|number|email|tel|date|checkbox
 *   'required' => bool
 *   'options'  => array of static choices (for type=select), OR
 *   'relation' => ['model' => FQCN, 'label_field' => 'name'] to populate a
 *                 select from another master entity's active records.
 */
return [

    'nav_groups' => [
        'Organization' => ['legal-entities', 'business-units', 'plants', 'locations', 'location-gst-registrations', 'warehouses'],
        'Warehouse Configuration' => ['warehouse-zones', 'racks', 'shelves', 'bins'],
        'Products & Quality' => ['item-categories', 'items', 'item-uom-conversions', 'uoms', 'hsn-taxes', 'temperature-classes', 'quality-parameters'],
        'Business Partners' => ['vendors', 'vendor-contacts', 'customers', 'transporters'],
        'Assets & Control' => ['machines', 'approval-workflows', 'approval-workflow-steps'],
        'Access & Configuration' => ['users', 'roles', 'number-series', 'sla-policies', 'document-rules', 'notification-templates', 'integration-connections'],
    ],

    'entities' => [

        'legal-entities' => [
            'model' => LegalEntity::class,
            'title' => 'Legal Entities',
            'singular' => 'Legal Entity',
            'eyebrow' => 'Organization Master',
            'description' => 'Maintain company-level legal, tax, currency and statutory information.',
            'icon' => 'LE',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'gstin', 'state', 'base_currency', 'approval_status', 'status'],
            'searchable' => ['code', 'name', 'gstin', 'pan', 'state'],
            'critical_fields' => ['gstin', 'pan', 'cin', 'base_currency'],
            'fields' => [
                ['name' => 'code', 'label' => 'Entity Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Legal Entity Name', 'type' => 'text', 'required' => true],
                ['name' => 'cin', 'label' => 'CIN / Registration No.', 'type' => 'text', 'required' => false],
                ['name' => 'pan', 'label' => 'PAN', 'type' => 'text', 'required' => false],
                ['name' => 'gstin', 'label' => 'Primary GSTIN', 'type' => 'text', 'required' => false],
                ['name' => 'country', 'label' => 'Country', 'type' => 'text', 'required' => false],
                ['name' => 'state', 'label' => 'Registered State', 'type' => 'text', 'required' => false],
                ['name' => 'base_currency', 'label' => 'Base Currency', 'type' => 'select', 'required' => true, 'options' => ['INR', 'USD', 'EUR']],
                ['name' => 'timezone', 'label' => 'Timezone', 'type' => 'select', 'required' => true, 'options' => ['Asia/Kolkata', 'UTC']],
                ['name' => 'fiscal_year', 'label' => 'Fiscal Year', 'type' => 'select', 'required' => true, 'options' => ['April-March', 'January-December']],
            ],
        ],

        'business-units' => [
            'model' => BusinessUnit::class,
            'title' => 'Business Units',
            'singular' => 'Business Unit',
            'eyebrow' => 'Organization Master',
            'description' => 'Define operating divisions, cost centers and accountable business owners.',
            'icon' => 'BU',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'legalEntity.name', 'head', 'cost_center', 'approval_status', 'status'],
            'searchable' => ['code', 'name', 'head', 'cost_center'],
            'critical_fields' => [],
            'fields' => [
                ['name' => 'code', 'label' => 'BU Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Business Unit Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_legal_entity_id', 'label' => 'Legal Entity', 'type' => 'select', 'required' => true, 'relation' => ['model' => LegalEntity::class, 'label_field' => 'name']],
                ['name' => 'head', 'label' => 'Business Head', 'type' => 'text', 'required' => false],
                ['name' => 'cost_center', 'label' => 'Cost Center', 'type' => 'text', 'required' => false],
                ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => false],
            ],
        ],

        'plants' => [
            'model' => Plant::class,
            'title' => 'Plants & Manufacturing Units',
            'singular' => 'Plant / Unit',
            'eyebrow' => 'Organization Master',
            'description' => 'Configure manufacturing units, warehouses, plant capacity and shift models.',
            'icon' => 'PL',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'businessUnit.name', 'location.name', 'plant_type', 'manager', 'approval_status', 'status'],
            'searchable' => ['code', 'name', 'manager'],
            'critical_fields' => [],
            'plant_scope_field' => 'id',
            'fields' => [
                ['name' => 'code', 'label' => 'Plant Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Plant / Unit Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_business_unit_id', 'label' => 'Business Unit', 'type' => 'select', 'required' => true, 'relation' => ['model' => BusinessUnit::class, 'label_field' => 'name']],
                ['name' => 'tan90_location_id', 'label' => 'Location', 'type' => 'select', 'required' => true, 'relation' => ['model' => Location::class, 'label_field' => 'name']],
                ['name' => 'plant_type', 'label' => 'Plant Type', 'type' => 'select', 'required' => true, 'options' => ['Manufacturing Unit', 'Warehouse', 'R&D Center', 'Office']],
                ['name' => 'manager', 'label' => 'Plant Manager', 'type' => 'text', 'required' => false],
                ['name' => 'phone', 'label' => 'Contact Phone', 'type' => 'tel', 'required' => false],
                ['name' => 'capacity', 'label' => 'Installed Capacity', 'type' => 'text', 'required' => false],
                ['name' => 'shift_model', 'label' => 'Shift Model', 'type' => 'select', 'required' => false, 'options' => ['General', '2 Shift', '3 Shift', '24x7']],
            ],
        ],

        'locations' => [
            'model' => Location::class,
            'title' => 'Locations & GST Registrations',
            'singular' => 'Location',
            'eyebrow' => 'Organization Master',
            'description' => 'Maintain business locations, addresses, GST registrations and GPS coordinates.',
            'icon' => 'LG',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'type', 'state', 'city', 'gstin', 'gst_status', 'approval_status'],
            'searchable' => ['code', 'name', 'state', 'city', 'gstin'],
            'critical_fields' => ['gstin', 'gst_status', 'state'],
            'plant_scope_field' => 'id',
            'fields' => [
                ['name' => 'code', 'label' => 'Location Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Location Name', 'type' => 'text', 'required' => true],
                ['name' => 'type', 'label' => 'Location Type', 'type' => 'select', 'required' => true, 'options' => ['Manufacturing', 'Warehouse', 'Office', 'Vendor Site']],
                ['name' => 'state', 'label' => 'State', 'type' => 'text', 'required' => true],
                ['name' => 'city', 'label' => 'City', 'type' => 'text', 'required' => true],
                ['name' => 'pincode', 'label' => 'PIN Code', 'type' => 'text', 'required' => false],
                ['name' => 'gstin', 'label' => 'GSTIN', 'type' => 'text', 'required' => false],
                ['name' => 'address', 'label' => 'Full Address', 'type' => 'textarea', 'required' => false],
                ['name' => 'latitude', 'label' => 'Latitude', 'type' => 'number', 'required' => false],
                ['name' => 'longitude', 'label' => 'Longitude', 'type' => 'number', 'required' => false],
                ['name' => 'gst_status', 'label' => 'GST Verification', 'type' => 'select', 'required' => true, 'options' => ['pending', 'verified', 'failed']],
            ],
        ],

        'location-gst-registrations' => [
            'model' => \App\Models\Tan90\MasterData\LocationGstRegistration::class,
            'title' => 'Location GST Registrations',
            'singular' => 'GST Registration',
            'eyebrow' => 'Organization Master',
            'description' => 'Track individual GSTIN registrations issued against a location.',
            'icon' => 'GR',
            'primary' => 'gstin',
            'code' => 'code',
            'columns' => ['code', 'location.name', 'gstin', 'gst_status', 'effective_from', 'approval_status', 'status'],
            'searchable' => ['code', 'gstin', 'legal_name'],
            'critical_fields' => ['gstin', 'gst_status'],
            'fields' => [
                ['name' => 'code', 'label' => 'Registration Code', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_location_id', 'label' => 'Location', 'type' => 'select', 'required' => true, 'relation' => ['model' => Location::class, 'label_field' => 'name']],
                ['name' => 'gstin', 'label' => 'GSTIN', 'type' => 'text', 'required' => true],
                ['name' => 'legal_name', 'label' => 'Registered Legal Name', 'type' => 'text', 'required' => false],
                ['name' => 'registration_type', 'label' => 'Registration Type', 'type' => 'text', 'required' => false],
                ['name' => 'effective_from', 'label' => 'Effective From', 'type' => 'date', 'required' => false],
                ['name' => 'gst_status', 'label' => 'GST Verification', 'type' => 'select', 'required' => true, 'options' => ['pending', 'verified', 'failed']],
            ],
        ],

        'warehouses' => [
            'model' => Warehouse::class,
            'title' => 'Warehouse Master',
            'singular' => 'Warehouse',
            'eyebrow' => 'Warehouse Configuration',
            'description' => 'Define warehouse purpose, capacity, temperature zone and bin controls.',
            'icon' => 'WH',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'plant.name', 'location.name', 'warehouse_type', 'capacity', 'bin_tracking', 'approval_status'],
            'searchable' => ['code', 'name', 'manager'],
            'critical_fields' => ['warehouse_type', 'bin_tracking'],
            'plant_scope_field' => 'tan90_plant_id',
            'fields' => [
                ['name' => 'code', 'label' => 'Warehouse Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Warehouse Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_plant_id', 'label' => 'Plant / Unit', 'type' => 'select', 'required' => true, 'relation' => ['model' => Plant::class, 'label_field' => 'name']],
                ['name' => 'tan90_location_id', 'label' => 'Location', 'type' => 'select', 'required' => true, 'relation' => ['model' => Location::class, 'label_field' => 'name']],
                ['name' => 'warehouse_type', 'label' => 'Warehouse Type', 'type' => 'select', 'required' => true, 'options' => ['Raw Material', 'Finished Goods', 'Central Distribution', 'QC Hold', 'Rejected', 'In Transit']],
                ['name' => 'manager', 'label' => 'Warehouse Manager', 'type' => 'text', 'required' => false],
                ['name' => 'capacity', 'label' => 'Capacity', 'type' => 'text', 'required' => false],
                ['name' => 'temperature_zone', 'label' => 'Temperature Zone', 'type' => 'text', 'required' => false],
                ['name' => 'bin_tracking', 'label' => 'Bin Tracking', 'type' => 'select', 'required' => true, 'options' => ['enabled', 'disabled']],
            ],
        ],

        'item-categories' => [
            'model' => ItemCategory::class,
            'title' => 'Item Categories',
            'singular' => 'Item Category',
            'eyebrow' => 'Product Master',
            'description' => 'Control product hierarchy, valuation, QC and tracking defaults.',
            'icon' => 'IC',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'parent', 'valuation_method', 'qc_required', 'batch_tracking', 'approval_status'],
            'searchable' => ['code', 'name', 'parent'],
            'critical_fields' => [],
            'fields' => [
                ['name' => 'code', 'label' => 'Category Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Category Name', 'type' => 'text', 'required' => true],
                ['name' => 'parent', 'label' => 'Parent Category', 'type' => 'text', 'required' => false],
                ['name' => 'valuation_method', 'label' => 'Valuation Method', 'type' => 'select', 'required' => true, 'options' => ['FIFO', 'Weighted Average', 'Standard Cost']],
                ['name' => 'qc_required', 'label' => 'QC Required', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No']],
                ['name' => 'batch_tracking', 'label' => 'Batch Tracking', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No', 'Optional']],
                ['name' => 'shelf_life', 'label' => 'Shelf Life Policy', 'type' => 'text', 'required' => false],
            ],
        ],

        'uoms' => [
            'model' => Uom::class,
            'title' => 'Units of Measure',
            'singular' => 'UOM',
            'eyebrow' => 'Product Master',
            'description' => 'Maintain base units, conversion factors and decimal precision.',
            'icon' => 'UM',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'type', 'base_uom', 'conversion_factor', 'decimal_places', 'approval_status'],
            'searchable' => ['code', 'name', 'base_uom'],
            'critical_fields' => ['conversion_factor', 'base_uom', 'decimal_places'],
            'fields' => [
                ['name' => 'code', 'label' => 'UOM Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'UOM Name', 'type' => 'text', 'required' => true],
                ['name' => 'type', 'label' => 'Measurement Type', 'type' => 'select', 'required' => true, 'options' => ['Weight', 'Count', 'Volume', 'Length', 'Area', 'Time']],
                ['name' => 'base_uom', 'label' => 'Base UOM', 'type' => 'text', 'required' => true],
                ['name' => 'conversion_factor', 'label' => 'Conversion Factor', 'type' => 'number', 'required' => true],
                ['name' => 'decimal_places', 'label' => 'Decimal Places', 'type' => 'number', 'required' => true],
            ],
        ],

        'items' => [
            'model' => \App\Models\Tan90\MasterData\Item::class,
            'title' => 'Item / SKU Master',
            'singular' => 'Item / SKU',
            'eyebrow' => 'Product Master',
            'description' => 'Authoritative item catalog for chemicals, packaging, panels and finished goods.',
            'icon' => 'SK',
            'primary' => 'masking_code',
            'code' => 'masking_code',
            'columns' => ['masking_code', 'category.name', 'uom.code', 'hsn', 'qc_required', 'approval_status'],
            'searchable' => ['sku', 'code', 'name', 'hsn', 'masking_code'],
            'critical_fields' => ['tan90_uom_id', 'hsn', 'standard_cost'],
            'importable' => true,
            'sample_csv' => 'item-master-sample.csv',
            // Client requirement: chemical/material identity must never be
            // shown outside this create/edit form - every other screen only
            // ever shows masking_code.
            'hidden_summary_fields' => ['name', 'sku', 'code'],
            'fields' => [
                ['name' => 'sku', 'label' => 'SKU (internal only)', 'type' => 'text', 'required' => true],
                ['name' => 'code', 'label' => 'Internal Code (internal only)', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Item Name (internal only)', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_item_category_id', 'label' => 'Category', 'type' => 'select', 'required' => true, 'relation' => ['model' => ItemCategory::class, 'label_field' => 'name']],
                ['name' => 'tan90_uom_id', 'label' => 'Base UOM', 'type' => 'select', 'required' => true, 'relation' => ['model' => Uom::class, 'label_field' => 'code']],
                ['name' => 'hsn', 'label' => 'HSN Code', 'type' => 'text', 'required' => false],
                ['name' => 'masking_code', 'label' => 'Masking Code', 'type' => 'text', 'required' => false],
                ['name' => 'qc_required', 'label' => 'QC Required', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No']],
                ['name' => 'batch_tracking', 'label' => 'Batch Tracking', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No', 'Optional']],
                ['name' => 'temperature', 'label' => 'Temperature Class', 'type' => 'text', 'required' => false],
                ['name' => 'storage', 'label' => 'Storage Condition', 'type' => 'text', 'required' => false],
                ['name' => 'reorder_level', 'label' => 'Reorder Level', 'type' => 'text', 'required' => false],
                ['name' => 'standard_cost', 'label' => 'Standard Cost', 'type' => 'number', 'required' => false],
            ],
        ],

        'item-uom-conversions' => [
            'model' => \App\Models\Tan90\MasterData\ItemUomConversion::class,
            'title' => 'Item UOM Conversions',
            'singular' => 'UOM Conversion',
            'eyebrow' => 'Product Master',
            'description' => 'Alternate units of measure for an item and their conversion factor to its base UOM.',
            'icon' => 'UC',
            'primary' => 'code',
            'code' => 'code',
            'columns' => ['code', 'item.masking_code', 'uom.code', 'conversion_factor', 'approval_status', 'status'],
            'searchable' => ['code'],
            'critical_fields' => ['conversion_factor'],
            'fields' => [
                ['name' => 'code', 'label' => 'Conversion Code', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_item_id', 'label' => 'Item', 'type' => 'select', 'required' => true, 'relation' => ['model' => \App\Models\Tan90\MasterData\Item::class, 'label_field' => 'masking_code']],
                ['name' => 'tan90_uom_id', 'label' => 'Alternate UOM', 'type' => 'select', 'required' => true, 'relation' => ['model' => Uom::class, 'label_field' => 'code']],
                ['name' => 'conversion_factor', 'label' => 'Conversion Factor to Base UOM', 'type' => 'number', 'required' => true],
            ],
        ],

        'vendors' => [
            'model' => Vendor::class,
            'title' => 'Vendor Master',
            'singular' => 'Vendor',
            'eyebrow' => 'Business Partner Master',
            'description' => 'Onboard, verify and manage vendors, portal access and commercial terms.',
            'icon' => 'VN',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'gstin', 'gst_status', 'category', 'state', 'payment_terms', 'approval_status'],
            'searchable' => ['code', 'name', 'gstin', 'category', 'city'],
            'critical_fields' => ['gstin', 'gst_status', 'payment_terms'],
            'importable' => true,
            'sample_csv' => 'vendor-master-sample.csv',
            'fields' => [
                ['name' => 'code', 'label' => 'Vendor Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Vendor Name', 'type' => 'text', 'required' => true],
                ['name' => 'gstin', 'label' => 'GSTIN', 'type' => 'text', 'required' => true],
                ['name' => 'gst_status', 'label' => 'GST Status', 'type' => 'select', 'required' => true, 'options' => ['pending', 'verified', 'failed']],
                ['name' => 'category', 'label' => 'Material Category', 'type' => 'text', 'required' => false],
                ['name' => 'state', 'label' => 'State', 'type' => 'text', 'required' => false],
                ['name' => 'city', 'label' => 'City', 'type' => 'text', 'required' => false],
                ['name' => 'contact', 'label' => 'Primary Contact', 'type' => 'text', 'required' => false],
                ['name' => 'phone', 'label' => 'Phone', 'type' => 'tel', 'required' => false],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => false],
                ['name' => 'payment_terms', 'label' => 'Payment Terms', 'type' => 'select', 'required' => false, 'options' => ['Advance', '15 Days', '30 Days', '45 Days', '60 Days']],
                ['name' => 'rating', 'label' => 'Vendor Rating', 'type' => 'number', 'required' => false],
                ['name' => 'portal_enabled', 'label' => 'Portal Enabled', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No']],
            ],
        ],

        'vendor-contacts' => [
            'model' => \App\Models\Tan90\MasterData\VendorContact::class,
            'title' => 'Vendor Contacts',
            'singular' => 'Vendor Contact',
            'eyebrow' => 'Business Partner Master',
            'description' => 'Maintain vendor contacts and notification responsibilities.',
            'icon' => 'VC',
            'primary' => 'name',
            'code' => 'email',
            'columns' => ['vendor.name', 'name', 'designation', 'email', 'phone', 'is_primary', 'approval_status'],
            'searchable' => ['name', 'email', 'designation'],
            'critical_fields' => [],
            'fields' => [
                ['name' => 'tan90_vendor_id', 'label' => 'Vendor', 'type' => 'select', 'required' => true, 'relation' => ['model' => Vendor::class, 'label_field' => 'name']],
                ['name' => 'name', 'label' => 'Contact Name', 'type' => 'text', 'required' => true],
                ['name' => 'designation', 'label' => 'Designation', 'type' => 'text', 'required' => false],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true],
                ['name' => 'phone', 'label' => 'Phone', 'type' => 'tel', 'required' => false],
                ['name' => 'is_primary', 'label' => 'Primary Contact', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No']],
                ['name' => 'notification_role', 'label' => 'Notifications', 'type' => 'text', 'required' => false],
            ],
        ],

        'warehouse-zones' => [
            'model' => WarehouseZone::class,
            'title' => 'Warehouse Zones',
            'singular' => 'Warehouse Zone',
            'eyebrow' => 'Warehouse Configuration',
            'description' => 'Physical zones within a warehouse (chemical safe, QC hold, packaging, ...).',
            'icon' => 'WZ',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'warehouse.name', 'zone_type', 'hazard_class', 'approval_status', 'status'],
            'searchable' => ['code', 'name', 'allowed_material'],
            'critical_fields' => ['hazard_class'],
            'plant_scope_field' => 'tan90_warehouse_id',
            'fields' => [
                ['name' => 'code', 'label' => 'Zone Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Zone Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_warehouse_id', 'label' => 'Warehouse', 'type' => 'select', 'required' => true, 'relation' => ['model' => Warehouse::class, 'label_field' => 'name']],
                ['name' => 'zone_type', 'label' => 'Zone Type', 'type' => 'select', 'required' => true, 'options' => ['Raw Material Zone', 'Chemical Safe Zone', 'Packaging Zone', 'QC Hold Zone', 'Defective Zone', 'Rejected Zone', 'Finished Goods Zone']],
                ['name' => 'allowed_material', 'label' => 'Allowed Material', 'type' => 'text', 'required' => false],
                ['name' => 'hazard_class', 'label' => 'Hazard Class', 'type' => 'select', 'required' => true, 'options' => ['None', 'Controlled', 'Segregated', 'Isolated']],
            ],
        ],

        'racks' => [
            'model' => Rack::class,
            'title' => 'Racks',
            'singular' => 'Rack',
            'eyebrow' => 'Warehouse Configuration',
            'description' => 'Racks within a warehouse zone.',
            'icon' => 'RK',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'zone.name', 'capacity', 'approval_status', 'status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => [],
            'fields' => [
                ['name' => 'code', 'label' => 'Rack Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Rack Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_warehouse_zone_id', 'label' => 'Warehouse Zone', 'type' => 'select', 'required' => true, 'relation' => ['model' => WarehouseZone::class, 'label_field' => 'name']],
                ['name' => 'capacity', 'label' => 'Capacity', 'type' => 'text', 'required' => false],
            ],
        ],

        'shelves' => [
            'model' => Shelf::class,
            'title' => 'Shelves',
            'singular' => 'Shelf',
            'eyebrow' => 'Warehouse Configuration',
            'description' => 'Shelves within a rack.',
            'icon' => 'SH',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'rack.name', 'capacity', 'approval_status', 'status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => [],
            'fields' => [
                ['name' => 'code', 'label' => 'Shelf Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Shelf Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_rack_id', 'label' => 'Rack', 'type' => 'select', 'required' => true, 'relation' => ['model' => Rack::class, 'label_field' => 'name']],
                ['name' => 'capacity', 'label' => 'Capacity', 'type' => 'text', 'required' => false],
            ],
        ],

        'bins' => [
            'model' => \App\Models\Tan90\MasterData\Bin::class,
            'title' => 'Bins',
            'singular' => 'Bin',
            'eyebrow' => 'Warehouse Configuration',
            'description' => 'The lowest-level storage location, on a shelf.',
            'icon' => 'BN',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'shelf.name', 'capacity', 'occupancy', 'approval_status', 'status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => [],
            'fields' => [
                ['name' => 'code', 'label' => 'Bin Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Bin Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_shelf_id', 'label' => 'Shelf', 'type' => 'select', 'required' => true, 'relation' => ['model' => Shelf::class, 'label_field' => 'name']],
                ['name' => 'capacity', 'label' => 'Capacity', 'type' => 'text', 'required' => false],
                ['name' => 'occupancy', 'label' => 'Current Occupancy', 'type' => 'text', 'required' => false],
                ['name' => 'temperature', 'label' => 'Temperature Rule', 'type' => 'text', 'required' => false],
            ],
        ],

        'hsn-taxes' => [
            'model' => \App\Models\Tan90\MasterData\HsnTaxRule::class,
            'title' => 'HSN & Tax Rules',
            'singular' => 'HSN Tax Rule',
            'eyebrow' => 'Tax Configuration',
            'description' => 'Map HSN classifications, GST rates and input-credit policy.',
            'icon' => 'TX',
            'primary' => 'description',
            'code' => 'hsn',
            'columns' => ['hsn', 'description', 'gst_rate', 'cess', 'input_credit', 'effective_from', 'approval_status'],
            'searchable' => ['hsn', 'description'],
            'critical_fields' => ['gst_rate', 'input_credit'],
            'fields' => [
                ['name' => 'hsn', 'label' => 'HSN Code', 'type' => 'text', 'required' => true],
                ['name' => 'description', 'label' => 'Description', 'type' => 'text', 'required' => true],
                ['name' => 'gst_rate', 'label' => 'GST Rate', 'type' => 'select', 'required' => true, 'options' => ['0%', '5%', '12%', '18%', '28%']],
                ['name' => 'cess', 'label' => 'Cess', 'type' => 'text', 'required' => false],
                ['name' => 'input_credit', 'label' => 'Input Credit', 'type' => 'select', 'required' => true, 'options' => ['Allowed', 'Blocked', 'Conditional']],
                ['name' => 'effective_from', 'label' => 'Effective From', 'type' => 'date', 'required' => true],
            ],
        ],

        'temperature-classes' => [
            'model' => \App\Models\Tan90\MasterData\TemperatureClass::class,
            'title' => 'Temperature & Storage Classes',
            'singular' => 'Temperature Class',
            'eyebrow' => 'Cold-Chain Configuration',
            'description' => 'Control storage temperature, excursion and monitoring policy.',
            'icon' => 'TP',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'min_temp', 'max_temp', 'excursion', 'monitoring', 'alarm_required', 'approval_status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => ['min_temp', 'max_temp'],
            'fields' => [
                ['name' => 'code', 'label' => 'Class Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Class Name', 'type' => 'text', 'required' => true],
                ['name' => 'min_temp', 'label' => 'Minimum Temperature', 'type' => 'text', 'required' => true],
                ['name' => 'max_temp', 'label' => 'Maximum Temperature', 'type' => 'text', 'required' => true],
                ['name' => 'excursion', 'label' => 'Allowed Excursion', 'type' => 'text', 'required' => false],
                ['name' => 'monitoring', 'label' => 'Monitoring Frequency', 'type' => 'select', 'required' => true, 'options' => ['Continuous', 'Hourly', 'Per Shift', 'Daily']],
                ['name' => 'alarm_required', 'label' => 'Alarm Required', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No']],
            ],
        ],

        'quality-parameters' => [
            'model' => \App\Models\Tan90\MasterData\QualityParameter::class,
            'title' => 'Quality Parameters',
            'singular' => 'Quality Parameter',
            'eyebrow' => 'Quality Configuration',
            'description' => 'Measurable acceptance criteria used by QC during inward and production.',
            'icon' => 'QC',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'itemCategory.name', 'data_type', 'unit', 'criticality', 'approval_status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => ['min_value', 'max_value'],
            'fields' => [
                ['name' => 'code', 'label' => 'Parameter Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Parameter Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_item_category_id', 'label' => 'Applicable Category', 'type' => 'select', 'required' => false, 'relation' => ['model' => ItemCategory::class, 'label_field' => 'name']],
                ['name' => 'data_type', 'label' => 'Data Type', 'type' => 'select', 'required' => true, 'options' => ['Decimal', 'Integer', 'Pass/Fail', 'Text', 'Option List']],
                ['name' => 'unit', 'label' => 'Unit', 'type' => 'text', 'required' => false],
                ['name' => 'min_value', 'label' => 'Minimum Value', 'type' => 'text', 'required' => false],
                ['name' => 'max_value', 'label' => 'Maximum Value', 'type' => 'text', 'required' => false],
                ['name' => 'sampling', 'label' => 'Sampling Plan', 'type' => 'text', 'required' => false],
                ['name' => 'criticality', 'label' => 'Criticality', 'type' => 'select', 'required' => true, 'options' => ['Critical', 'Major', 'Minor']],
            ],
        ],

        'customers' => [
            'model' => \App\Models\Tan90\MasterData\Customer::class,
            'title' => 'Customer Master',
            'singular' => 'Customer',
            'eyebrow' => 'Business Partner Master',
            'description' => 'Maintain customer identity, GST, segment and credit controls.',
            'icon' => 'CU',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'gstin', 'segment', 'state', 'city', 'credit_limit', 'approval_status'],
            'searchable' => ['code', 'name', 'gstin', 'city'],
            'critical_fields' => ['gstin', 'credit_limit'],
            'fields' => [
                ['name' => 'code', 'label' => 'Customer Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Customer Name', 'type' => 'text', 'required' => true],
                ['name' => 'gstin', 'label' => 'GSTIN', 'type' => 'text', 'required' => false],
                ['name' => 'segment', 'label' => 'Segment', 'type' => 'select', 'required' => true, 'options' => ['Pharma', 'Frozen Foods', 'Dairy', 'Agriculture', 'E-commerce', 'Other']],
                ['name' => 'state', 'label' => 'State', 'type' => 'text', 'required' => false],
                ['name' => 'city', 'label' => 'City', 'type' => 'text', 'required' => false],
                ['name' => 'credit_limit', 'label' => 'Credit Limit', 'type' => 'text', 'required' => false],
                ['name' => 'payment_terms', 'label' => 'Payment Terms', 'type' => 'text', 'required' => false],
                ['name' => 'sales_owner', 'label' => 'Sales Owner', 'type' => 'text', 'required' => false],
            ],
        ],

        'transporters' => [
            'model' => \App\Models\Tan90\MasterData\Transporter::class,
            'title' => 'Transporter Master',
            'singular' => 'Transporter',
            'eyebrow' => 'Business Partner Master',
            'description' => 'Logistics partners, contact, GPS and insurance readiness.',
            'icon' => 'TR',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'gstin', 'service_type', 'contact', 'gps_tracking', 'insurance', 'approval_status'],
            'searchable' => ['code', 'name', 'gstin'],
            'critical_fields' => [],
            'fields' => [
                ['name' => 'code', 'label' => 'Transporter Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Transporter Name', 'type' => 'text', 'required' => true],
                ['name' => 'gstin', 'label' => 'GSTIN', 'type' => 'text', 'required' => false],
                ['name' => 'service_type', 'label' => 'Service Type', 'type' => 'text', 'required' => false],
                ['name' => 'contact', 'label' => 'Contact Person', 'type' => 'text', 'required' => false],
                ['name' => 'phone', 'label' => 'Phone', 'type' => 'tel', 'required' => false],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => false],
                ['name' => 'gps_tracking', 'label' => 'GPS Tracking', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No']],
                ['name' => 'insurance', 'label' => 'Insurance Validity', 'type' => 'text', 'required' => false],
            ],
        ],

        'machines' => [
            'model' => \App\Models\Tan90\MasterData\Machine::class,
            'title' => 'Machines & Equipment',
            'singular' => 'Machine',
            'eyebrow' => 'Asset Master',
            'description' => 'Production and cold-chain equipment with capacity and maintenance policy.',
            'icon' => 'MC',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'plant.name', 'machine_type', 'capacity', 'maintenance_cycle', 'iot_enabled', 'approval_status'],
            'searchable' => ['code', 'name', 'serial_no'],
            'critical_fields' => [],
            'plant_scope_field' => 'tan90_plant_id',
            'fields' => [
                ['name' => 'code', 'label' => 'Machine Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Machine Name', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_plant_id', 'label' => 'Plant', 'type' => 'select', 'required' => true, 'relation' => ['model' => Plant::class, 'label_field' => 'name']],
                ['name' => 'machine_type', 'label' => 'Machine Type', 'type' => 'text', 'required' => true],
                ['name' => 'manufacturer', 'label' => 'Manufacturer', 'type' => 'text', 'required' => false],
                ['name' => 'model', 'label' => 'Model', 'type' => 'text', 'required' => false],
                ['name' => 'serial_no', 'label' => 'Serial Number', 'type' => 'text', 'required' => false],
                ['name' => 'commissioned', 'label' => 'Commissioning Date', 'type' => 'date', 'required' => false],
                ['name' => 'capacity', 'label' => 'Capacity', 'type' => 'text', 'required' => false],
                ['name' => 'maintenance_cycle', 'label' => 'Maintenance Cycle', 'type' => 'text', 'required' => false],
                ['name' => 'iot_enabled', 'label' => 'IoT Enabled', 'type' => 'select', 'required' => true, 'options' => ['Yes', 'No']],
            ],
        ],

        'approval-workflows' => [
            'model' => ApprovalWorkflow::class,
            'title' => 'Approval Workflows',
            'singular' => 'Approval Workflow',
            'eyebrow' => 'Governance Configuration',
            'description' => 'Configure maker-checker approvals, steps, SLAs and escalation.',
            'icon' => 'WF',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'module', 'trigger', 'sla', 'version_label', 'approval_status'],
            'searchable' => ['code', 'name', 'module'],
            'critical_fields' => [],
            'no_approval' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'Workflow Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Workflow Name', 'type' => 'text', 'required' => true],
                ['name' => 'module', 'label' => 'Module', 'type' => 'text', 'required' => true],
                ['name' => 'trigger', 'label' => 'Trigger', 'type' => 'text', 'required' => true],
                ['name' => 'steps', 'label' => 'Approval Steps (summary)', 'type' => 'textarea', 'required' => false],
                ['name' => 'sla', 'label' => 'SLA', 'type' => 'text', 'required' => false],
                ['name' => 'escalation', 'label' => 'Escalation Role', 'type' => 'text', 'required' => false],
                ['name' => 'version_label', 'label' => 'Version', 'type' => 'text', 'required' => false],
                ['name' => 'approval_status', 'label' => 'Workflow Status', 'type' => 'select', 'required' => true, 'options' => ['draft', 'active', 'inactive']],
            ],
        ],

        'approval-workflow-steps' => [
            'model' => \App\Models\Tan90\MasterData\ApprovalWorkflowStep::class,
            'title' => 'Approval Workflow Steps',
            'singular' => 'Workflow Step',
            'eyebrow' => 'Governance Configuration',
            'description' => 'Ordered reviewer roles for a workflow. Descriptive/config only in this build - ApprovalService still runs a single maker-checker step; see docs/PHASE_2_SCOPE.md.',
            'icon' => 'WS',
            'primary' => 'step_role',
            'code' => 'code',
            'columns' => ['code', 'workflow.name', 'step_order', 'step_role', 'sla_hours', 'status'],
            'searchable' => ['code', 'step_role'],
            'critical_fields' => [],
            'no_approval' => true,
            'no_soft_delete' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'Step Code', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_approval_workflow_id', 'label' => 'Workflow', 'type' => 'select', 'required' => true, 'relation' => ['model' => ApprovalWorkflow::class, 'label_field' => 'name']],
                ['name' => 'step_order', 'label' => 'Step Order', 'type' => 'number', 'required' => true],
                ['name' => 'step_role', 'label' => 'Reviewer Role', 'type' => 'text', 'required' => true],
                ['name' => 'sla_hours', 'label' => 'SLA Hours', 'type' => 'number', 'required' => false],
            ],
        ],

        'number-series' => [
            'model' => \App\Models\Tan90\MasterData\NumberSeries::class,
            'title' => 'Number Series',
            'singular' => 'Number Series',
            'eyebrow' => 'System Configuration',
            'description' => 'Automatic codes and document numbering by module. Used by StoreMasterDataRequest to auto-fill a blank code field on create.',
            'icon' => 'NS',
            'primary' => 'module',
            'code' => 'module',
            'columns' => ['module', 'prefix', 'pattern', 'next_number', 'reset_policy', 'preview', 'status'],
            'searchable' => ['module', 'prefix'],
            'critical_fields' => [],
            'no_approval' => true,
            'no_soft_delete' => true,
            'fields' => [
                ['name' => 'module', 'label' => 'Module (matches entity title)', 'type' => 'text', 'required' => true],
                ['name' => 'prefix', 'label' => 'Prefix', 'type' => 'text', 'required' => false],
                ['name' => 'pattern', 'label' => 'Pattern', 'type' => 'text', 'required' => true],
                ['name' => 'next_number', 'label' => 'Next Number', 'type' => 'number', 'required' => true],
                ['name' => 'reset_policy', 'label' => 'Reset Policy', 'type' => 'select', 'required' => true, 'options' => ['Never', 'Yearly', 'Monthly', 'Daily']],
                ['name' => 'preview', 'label' => 'Preview', 'type' => 'text', 'required' => false],
            ],
        ],

        'sla-policies' => [
            'model' => \App\Models\Tan90\MasterData\SlaPolicy::class,
            'title' => 'SLA & Escalation Policies',
            'singular' => 'SLA Policy',
            'eyebrow' => 'Governance Configuration',
            'description' => 'Response deadlines, warning thresholds and escalation owners.',
            'icon' => 'SL',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'applies_to', 'target', 'escalate_at', 'escalation_role', 'status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => [],
            'no_approval' => true,
            'no_soft_delete' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'SLA Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'SLA Name', 'type' => 'text', 'required' => true],
                ['name' => 'applies_to', 'label' => 'Applies To', 'type' => 'text', 'required' => true],
                ['name' => 'target', 'label' => 'Target Duration', 'type' => 'text', 'required' => true],
                ['name' => 'warning_at', 'label' => 'Warning At', 'type' => 'text', 'required' => false],
                ['name' => 'escalate_at', 'label' => 'Escalate At', 'type' => 'text', 'required' => false],
                ['name' => 'escalation_role', 'label' => 'Escalation Role', 'type' => 'text', 'required' => false],
                ['name' => 'calendar', 'label' => 'Calendar', 'type' => 'select', 'required' => true, 'options' => ['24x7', 'Business Hours']],
            ],
        ],

        'document-rules' => [
            'model' => \App\Models\Tan90\MasterData\DocumentRule::class,
            'title' => 'Document Rules',
            'singular' => 'Document Rule',
            'eyebrow' => 'Compliance Configuration',
            'description' => 'Required evidence, file policy and retention by master entity.',
            'icon' => 'DR',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'entity', 'max_size', 'allowed_types', 'retention', 'status'],
            'searchable' => ['code', 'name', 'entity'],
            'critical_fields' => [],
            'no_approval' => true,
            'no_soft_delete' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'Rule Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Rule Name', 'type' => 'text', 'required' => true],
                ['name' => 'entity', 'label' => 'Master Entity', 'type' => 'text', 'required' => true],
                ['name' => 'mandatory', 'label' => 'Mandatory Documents', 'type' => 'textarea', 'required' => true],
                ['name' => 'optional', 'label' => 'Optional Documents', 'type' => 'textarea', 'required' => false],
                ['name' => 'max_size', 'label' => 'Maximum File Size', 'type' => 'text', 'required' => false],
                ['name' => 'allowed_types', 'label' => 'Allowed Types', 'type' => 'text', 'required' => false],
                ['name' => 'retention', 'label' => 'Retention Period', 'type' => 'text', 'required' => false],
            ],
        ],

        'notification-templates' => [
            'model' => \App\Models\Tan90\MasterData\NotificationTemplate::class,
            'title' => 'Notification Templates',
            'singular' => 'Notification Template',
            'eyebrow' => 'Communication Configuration',
            'description' => 'Event-driven notification subjects, recipients and channels.',
            'icon' => 'NT',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'channel', 'subject', 'recipient', 'trigger_event', 'status'],
            'searchable' => ['code', 'name', 'subject'],
            'critical_fields' => [],
            'no_approval' => true,
            'no_soft_delete' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'Template Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Template Name', 'type' => 'text', 'required' => true],
                ['name' => 'channel', 'label' => 'Channel', 'type' => 'select', 'required' => true, 'options' => ['Email', 'In-App', 'Email + In-App', 'SMS', 'WhatsApp']],
                ['name' => 'subject', 'label' => 'Subject', 'type' => 'text', 'required' => true],
                ['name' => 'recipient', 'label' => 'Recipient Rule', 'type' => 'text', 'required' => true],
                ['name' => 'trigger_event', 'label' => 'Trigger Event', 'type' => 'text', 'required' => true],
                ['name' => 'language', 'label' => 'Language', 'type' => 'select', 'required' => true, 'options' => ['English', 'Hindi']],
            ],
        ],

        'integration-connections' => [
            'model' => \App\Models\Tan90\MasterData\IntegrationConnection::class,
            'title' => 'API & Integration Connections',
            'singular' => 'Integration Connection',
            'eyebrow' => 'Integration Configuration',
            'description' => 'Configured providers, environment and connection health, without exposing secrets (see Module Settings for credentials).',
            'icon' => 'AP',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'type', 'environment', 'health', 'last_tested_at', 'status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => [],
            'no_approval' => true,
            'no_soft_delete' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'Connection Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Connection Name', 'type' => 'text', 'required' => true],
                ['name' => 'type', 'label' => 'Connection Type', 'type' => 'select', 'required' => true, 'options' => ['REST API', 'SOAP', 'OAuth 2.0', 'SMTP', 'SFTP', 'Browser SDK']],
                ['name' => 'base_url', 'label' => 'Base URL / Host', 'type' => 'text', 'required' => false],
                ['name' => 'auth', 'label' => 'Authentication', 'type' => 'text', 'required' => false],
                ['name' => 'environment', 'label' => 'Environment', 'type' => 'select', 'required' => true, 'options' => ['Demo', 'Staging', 'Production', 'Future']],
            ],
        ],

        'data-quality-rules' => [
            'model' => \App\Models\Tan90\MasterData\DataQualityRule::class,
            'title' => 'Data Quality Rules',
            'singular' => 'Data Quality Rule',
            'eyebrow' => 'Data Governance',
            'description' => 'Catalog of checks run by the Data Quality scan (see /tan90/master-data/data-quality).',
            'icon' => 'DQ',
            'primary' => 'description',
            'code' => 'code',
            'columns' => ['code', 'entity', 'description', 'default_severity', 'status'],
            'searchable' => ['code', 'entity', 'description'],
            'critical_fields' => [],
            'no_approval' => true,
            'no_soft_delete' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'Rule Code', 'type' => 'text', 'required' => true],
                ['name' => 'entity', 'label' => 'Entity', 'type' => 'text', 'required' => true],
                ['name' => 'description', 'label' => 'Description', 'type' => 'text', 'required' => true],
                ['name' => 'default_severity', 'label' => 'Default Severity', 'type' => 'select', 'required' => true, 'options' => ['critical', 'high', 'medium', 'low']],
            ],
        ],

        'roles' => [
            'model' => Role::class,
            'title' => 'Roles',
            'singular' => 'Role',
            'eyebrow' => 'Access Control',
            'description' => 'Define functional roles and data scope. Capabilities are set on the Permission Matrix screen.',
            'icon' => 'RL',
            'primary' => 'name',
            'code' => 'code',
            'columns' => ['code', 'name', 'type', 'data_scope', 'status'],
            'searchable' => ['code', 'name'],
            'critical_fields' => [],
            'no_approval' => true,
            'fields' => [
                ['name' => 'code', 'label' => 'Role Code', 'type' => 'text', 'required' => true],
                ['name' => 'name', 'label' => 'Role Name', 'type' => 'text', 'required' => true],
                ['name' => 'type', 'label' => 'Role Type', 'type' => 'select', 'required' => true, 'options' => ['System', 'Operational', 'Read Only', 'External']],
                ['name' => 'data_scope', 'label' => 'Data Scope', 'type' => 'text', 'required' => false],
            ],
        ],

        'users' => [
            'model' => \App\Models\Tan90\MasterData\UserProfile::class,
            'title' => 'Users',
            'singular' => 'User',
            'eyebrow' => 'Access Control',
            'description' => 'Manage user identity, role, data scope and MFA readiness.',
            'icon' => 'US',
            'primary' => 'employee_id',
            'code' => 'employee_id',
            'columns' => ['employee_id', 'user.name', 'user.email', 'role.name', 'department', 'mfa_status', 'status'],
            'searchable' => ['employee_id', 'department'],
            'critical_fields' => [],
            'no_approval' => true,
            'user_managed_elsewhere' => true,
            'fields' => [
                ['name' => 'employee_id', 'label' => 'Employee ID', 'type' => 'text', 'required' => true],
                ['name' => 'tan90_role_id', 'label' => 'Role', 'type' => 'select', 'required' => true, 'relation' => ['model' => Role::class, 'label_field' => 'name']],
                ['name' => 'assigned_plant_id', 'label' => 'Assigned Plant', 'type' => 'select', 'required' => false, 'relation' => ['model' => Plant::class, 'label_field' => 'name']],
                ['name' => 'assigned_location_id', 'label' => 'Assigned Location', 'type' => 'select', 'required' => false, 'relation' => ['model' => Location::class, 'label_field' => 'name']],
                ['name' => 'department', 'label' => 'Department', 'type' => 'text', 'required' => false],
                ['name' => 'mfa_status', 'label' => 'MFA Status', 'type' => 'select', 'required' => true, 'options' => ['enabled', 'pending', 'disabled']],
            ],
        ],

    ],

];
